import Providers from '@/components/progress-bar/provider';
import { Toaster } from '@/components/ui/toaster';
import { AuthProvider } from '@/providers/AuthProvider';
import StoreProvider from '@/providers/StoreProvider';
import type { Metadata } from 'next';
import { Poly } from 'next/font/google';
import './globals.css';
import { CartProvider } from '@/components/CartContext';

export const poly = Poly({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-poly',
});

// const inter = Inter({ subsets: ['latin'] });

// export const work_sans = Work_Sans({
//   subsets: ["latin"],
//   weight: ["400"],
// })

export const metadata: Metadata = {
  title: 'Patera Pottery',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poly.className}>
        <StoreProvider>
          <AuthProvider>
            <Providers>
              <CartProvider>
              {/* <Navbar /> */}
              {children}
              <Toaster />
              {/* <Footer /> */}
              </CartProvider>
            </Providers>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
